### ISSUE TITLE
Crashes after recent update

### ISSUE THREAD

**Issue by ctron** [flathub/org.kde.kdenlive#148]
Kdenlive crashes after the recent update (`21.08.1`).

The output is:

~~~
$ flatpak run org.kde.kdenlive
=== /// CANNOT ACCESS SPEECH DICTIONARIES FOLDER
=================BUILDING PROFILE REPOSITORY

========================
Invalid metadata for  "telecide"
Failed to parse "telecide"
Invalid metadata for  "avcolour_space"
Failed to parse "avcolour_space"
Invalid metadata for  "avcolor_space"
Failed to parse "avcolor_space"
Invalid metadata for  "avdeinterlace"
Failed to parse "avdeinterlace"
Invalid metadata for  "swscale"
Failed to parse "swscale"
Invalid metadata for  "swresample"
Failed to parse "swresample"
Invalid metadata for  "audiochannels"
Failed to parse "audiochannels"
Invalid metadata for  "audioconvert"
Failed to parse "audioconvert"
Invalid metadata for  "imageconvert"
Failed to parse "imageconvert"
Invalid metadata for  "deinterlace"
Failed to parse "deinterlace"
Invalid metadata for  "jack"
Failed to parse "jack"
Invalid metadata for  "glsl.manager"
Failed to parse "glsl.manager"
Invalid metadata for  "movit.convert"
Failed to parse "movit.convert"
Invalid metadata for  "movit.crop"
Failed to parse "movit.crop"
Invalid metadata for  "movit.resample"
Failed to parse "movit.resample"
Invalid metadata for  "movit.resize"
Failed to parse "movit.resize"
Unknown asset "avfilter.acompressor"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/acompressor.xml"
Unknown asset "avfilter.aecho"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/aecho.xml"
Unknown asset "avfilter.agate"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/agate.xml"
Unknown asset "avfilter.atadenoise"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_atadenoise.xml"
Unknown asset "avfilter.bwdif"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_bwdif.xml"
Unknown asset "avfilter.deblock"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_deblock.xml"
Unknown asset "avfilter.dedot"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_dedot.xml"
Unknown asset "avfilter.deflate"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_deflate.xml"
Unknown asset "avfilter.derain"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_derain.xml"
Unknown asset "avfilter.doubleweave"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_doubleweave.xml"
Unknown asset "avfilter.field"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_field.xml"
Unknown asset "avfilter.framestep"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_framestep.xml"
Unknown asset "avfilter.fspp"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_fspp.xml"
Unknown asset "avfilter.graphmonitor"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_graphmonitor.xml"
Unknown asset "avfilter.hqdn3d"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_hqdn3d.xml"
Unknown asset "avfilter.inflate"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_inflate.xml"
Unknown asset "avfilter.lagfun"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_lagfun.xml"
Unknown asset "avfilter.random"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_random.xml"
Unknown asset "avfilter.removegrain"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_removegrain.xml"
Unknown asset "avfilter.separatefields"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_separatefields.xml"
Unknown asset "avfilter.shuffleplanes"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_shuffleplanes.xml"
Unknown asset "avfilter.sr"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_sr.xml"
Unknown asset "avfilter.tmix"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_tmix.xml"
Unknown asset "avfilter.w3fdif"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_w3fdif.xml"
Unknown asset "avfilter.weave"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_weave.xml"
Unknown asset "avfilter.yadif"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/avfilter_yadif.xml"
Unknown asset "frei0r.baltan"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_baltan.xml"
Unknown asset "frei0r.bgsubtract0r"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_bgsubtract0r.xml"
Unknown asset "frei0r.delay0r"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_delay0r.xml"
Unknown asset "frei0r.delaygrab"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_delaygrab.xml"
Unknown asset "frei0r.facebl0r"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_facebl0r.xml"
Unknown asset "frei0r.facedetect"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_facedetect.xml"
Unknown asset "frei0r.lightgraffiti"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_lightgraffiti.xml"
Unknown asset "frei0r.lightgraffiti"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/frei0r_lightgraffiti.xml"
Unknown asset "movit.unsharp_mask"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/movit_unsharp_mask.xml"
Unknown asset "region"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/region.xml"
Unknown asset "timewarp"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/speed.xml"
Unknown asset "region"
~~~

**Comment by ctron** [comment]
Ok it looks like this is a KDE platform issue. It wasn't a problem of Kdenlive, but I had to downgrade the KDE platform:

~~~
flatpak update --commit=4820a00d9526d39b6a370476bdba08843557d24efa9eff0dc70b401a57b5bd09 runtime/org.kde.Platform/x86_64/5.15
~~~

**Comment by tsdgeos** [comment]
I have just run flatpak update and flatpak run org.kde.kdenlive still works fine :/

**Comment by ctron** [comment]
For me it is reproducible to crash. :shrug:

**Comment by aleixpol** [comment]
I cannot reproduce either. Can you maybe provide a backtrace?

```
$ flatpak run --devel --command=sh org.kde.kdenlive
$ gdb kdenlive
(gdb) run
# let it crash....
(gdb) where
```

**Comment by ctron** [comment]
~~~
…
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/region.xml"
Unknown asset "timewarp"
==== PARSING ABORTED FOR:  "/app/share/kdenlive/effects/speed.xml"
Unknown asset "region"
[New Thread 0x7ffef4971700 (LWP 62)]
[Thread 0x7ffef4971700 (LWP 62) exited]
[New Thread 0x7ffef4971700 (LWP 63)]
[Detaching after fork from child process 64]

--Type <RET> for more, q to quit, c to continue without paging--
Thread 56 "QQmlThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef4971700 (LWP 63)]
0x00007ffff5a7ecc0 in QQmlType::QQmlType(QQmlType const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) where
#0  0x00007ffff5a7ecc0 in QQmlType::QQmlType(QQmlType const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#1  0x00007ffff5ae0eed in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#2  0x00007ffff5ae3044 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#3  0x00007ffff5ae33e9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#4  0x00007ffff5ae3ef5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#5  0x00007ffff5adf79f in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#6  0x00007ffff5a37815 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007ffff5a3deaf in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#8  0x00007ffff5a2ce05 in QQmlDataBlob::tryDone() () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#9  0x00007ffff5a86ff5 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#10 0x00007ffff5a876b2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#11 0x00007ffff5a8841c in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#12 0x00007ffff5a887dc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#13 0x00007ffff5a88fb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#14 0x00007ffff5a3cde6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#15 0x00007ffff5a3f91d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#16 0x00007ffff5a8727a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007ffff5a876b2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007ffff5a8841c in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007ffff5a887dc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007ffff5a88fb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007ffff5a3cde6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#22 0x00007ffff5a3f91d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#23 0x00007ffff5a8727a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#24 0x00007ffff5a876b2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#25 0x00007ffff5a8841c in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#26 0x00007ffff5a887dc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#27 0x00007ffff5a88fb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#28 0x00007ffff5a3c373 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#29 0x00007ffff5a3f91d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#30 0x00007ffff5a8727a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#31 0x00007ffff5a876b2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#32 0x00007ffff5a8841c in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#33 0x00007ffff5a887dc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#34 0x00007ffff5a88fb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#35 0x00007ffff5a3cde6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#36 0x00007ffff5a3f91d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#37 0x00007ffff5a8727a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#38 0x00007ffff5a876b2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#39 0x00007ffff5a8841c in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#40 0x00007ffff5a473dd in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#41 0x00007ffff5af9ccf in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#42 0x00007ffff5afa4a2 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#43 0x00007ffff651017f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff52f5b5a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007ffff52f8591 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007ffff534d8b3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007ffff3f9785b in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff3f97b08 in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff3f97bd3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007ffff534cf3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007ffff52f450b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff510457e in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#53 0x00007ffff5af9985 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#54 0x00007ffff51056c1 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#55 0x00007ffff439a4d2 in start_thread () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#56 0x00007ffff4c1a323 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

~~~

**Comment by ctron** [comment]
One of the recent updates seems to have fixed it.
