### ISSUE TITLE
Nvidia driver: crash at startup

### ISSUE THREAD

**Issue by Bleuzen** [flathub/org.kde.kdenlive#4]
Hi, I installed this and wanted to start it on my Manjaro KDE system.
But Kdenlive doesn't start. Instead it prints this:

```
Qt: Session management error: Could not open network socket
Icon theme "ubuntu-mono-dark" not found.
Icon theme "ubuntu-mono-dark" not found.
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x55efa60. Receiver '' (of type 'QOffscreenSurface') was created in thread 0x0x29c2cf0", file kernel/qcoreapplication.cpp, line 563
```

**Comment by eszlari** [comment]
Do you have a Nvidia card?

**Comment by Bleuzen** [comment]
yes

**Comment by eszlari** [comment]
Try the nouveau mesa driver. This is a known bug.

```
(gdb) backtrace
#0  0x00000035e323304f in raise () at /lib/libc.so.6
#1  0x00000035e323447a in abort () at /lib/libc.so.6
#2  0x00007fce37b1703c in  () at /lib/libQt5Core.so.5
#3  0x00007fce37b179f9 in  () at /lib/libQt5Core.so.5
#4  0x00007fce37b125cd in qt_int_sqrt(unsigned int) () at /lib/libQt5Core.so.5
#5  0x00007fce37cfca95 in
QCoreApplicationPrivate::checkReceiverThread(QObject*) () at
/lib/libQt5Core.so.5
#6  0x00007fce3969a3ec in QApplication::notify(QObject*, QEvent*) ()
at /lib/libQt5Widgets.so.5
#7  0x00007fce37cfd04c in QCoreApplication::notifyInternal2(QObject*,
QEvent*) () at /lib/libQt5Core.so.5
#8  0x00007fce380942ce in QOffscreenSurface::create() () at /lib/libQt5Gui.so.5
#9  0x00000000008198ad in GLWidget::initializeGL() (this=0x3a4a440) at
/run/build/kdenlive/src/monitor/glwidget.cpp:152
#10 0x0000000000826ce6 in
QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>,
void, void (GLWidget::*)()>::call(void (GLWidget::*)(), GLWidget*,
void**) (f=(void (GLWidget::*)(GLWidget * const)) 0x8197bc
<GLWidget::initializeGL()>, o=0x3a4a440, arg=0x7fce04c6ab40) at
/usr/include/QtCore/qobjectdefs_impl.h:136
#11 0x0000000000826ad4 in QtPrivate::FunctionPointer<void
(GLWidget::*)()>::call<QtPrivate::List<>, void>(void (GLWidget::*)(),
GLWidget*, void**) (f=(void (GLWidget::*)(GLWidget * const)) 0x8197bc
<GLWidget::initializeGL()>, o=0x3a4a440, arg=0x7fce04c6ab40) at
/usr/include/QtCore/qobjectdefs_impl.h:169
```

**Comment by Bleuzen** [comment]
Ah ok, but this is not a good solution for me. I need the Nvidia driver because of better performance and compatibility with more graphics and video software / games.

I think I will use the AppImage for now until this got fixed.

Anyway, thanks for the information :D

**Comment by eszlari** [comment]
fixed in: https://github.com/flathub/org.kde.kdenlive/commit/21d120d78758ac03135e61e3daa80e6b193d0567
